version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building the application..."
      - python -m py_compile app/main.py

  post_build:
    commands:
      - echo "Build complete, preparing artifact..."
      - zip -r deploy.zip .

artifacts:
  files:
    - deploy.zip
    - buildspec.yml
